<a href="https://colab.research.google.com/github/21JN1A4218/Machine-learning-Notes/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [5]:
demo =[10,20,30]
print(demo)
np.array(demo)


[10, 20, 30]


array([10, 20, 30])

In [7]:
demo2=[10,20,"30"]
np.array(demo2)

array(['10', '20', '30'], dtype='<U21')

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(5,int)
x1=np.ones(5)
print(x1)

[1. 1. 1. 1. 1.]


In [11]:
x=np.zeros(10)
x.dtype

dtype('float64')

In [12]:
y=np.zeros(10,int)
y.dtype

dtype('int64')