<a href="https://colab.research.google.com/github/21JN1A4218/Machine-learning-Notes/blob/main/NUMPY2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
x5=np.ones(5)
x5[3]=2
print(x5)

[1. 1. 1. 2. 1.]


In [4]:
x5=np.ones(5,int)
x5[3]=2
print(x5)

[1 1 1 2 1]


print 3d array

In [5]:
new_array=np.zeros((3,4,5))
print(new_array)


[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [6]:
new_array=np.zeros((3,4,5))
print(new_array)
new_array[0][1][2]

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


0.0

In [7]:
new_array=np.zeros((3,4,5))
print(new_array)
new_array[0][1]

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


array([0., 0., 0., 0., 0.])

In [8]:
new_array=np.zeros((3,4,5))
print(new_array)
new_array[0]

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

shape of an array

In [9]:
new_array.shape

(3, 4, 5)

slicing

In [11]:
a=np.zeros(5)
print(a)
a[2:4]

[0. 0. 0. 0. 0.]


array([0., 0.])

In [13]:
twoD_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD_array[2])

[7 8 9]


In [14]:
twoD_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD_array[2])

[2 5 8]


In [15]:
twoD_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD_array[1:3,0])


[4 7]


In [16]:
x=np.array([1,2,3])
y=np.array([3,5,6])
x=x+10
print(x)
print(x+y)

[11 12 13]
[14 17 19]


In [18]:
z=np.array([200,300,400])
print(y+z)

[203 305 406]


In [20]:
print(x*2)
print(x*y)
print(x**3)

[22 24 26]
[33 60 78]
[1331 1728 2197]


In [23]:
print(x.mean())
print(x.sum())

12.0
36


In [30]:

p1=np.array([2,2,2])
p2=np.array([1,1,1])
val=((p1-p2)**2).sum()
print(val)
m.sqrt(val)



3


1.7320508075688772

In [31]:
pts=np.array([4,5,6,7])
value1=((pts-pts.mean())**2).sum()
print(value1)

5.0
